source 'https://rubygems.org'

gem 'linkeddata', '>= 3.0.1'
gem 'json-ld-preloaded'
gem 'rspec'
gem 'rake'
gem 'nokogiri', '>= 1.10.5'
gem 'equivalent-xml', '>= 0.6.0'

group :debug do
  gem 'byebug'
end
